os:
  - Visual Studio 2019
  
platform:
  - x64
  - x86
  
branches:
  only:
    - master
    
install:
  - cd ..
  - dir
  - curl -fsS -o pin.zip https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.30-98830-g1d7b601b3-msvc-windows.zip
  - 7z x pin.zip
  - dir
  - cd pin-3.30-98830-g1d7b601b3-msvc-windows
  - dir
  - cd source
  - cd tools
  - git clone https://github.com/hasherezade/tiny_tracer
  - cd tiny_tracer

build:
  verbosity: detailed

environment:
  buildConfig: $(CONFIGURATION)
  buildPlatform: $(PLATFORM)

configuration:
  - Release
    
build_script:
  - ps: $PlatformToolset = "v142"
  - ps: (Get-Content TinyTracer.vcxproj) | %{$_ -replace "v110", $PlatformToolset} | Set-Content TinyTracer.vcxproj
  - ps: msbuild TinyTracer.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"
  
after_build:
  - dir
  - if [%buildPlatform%]==[x64] ( cp x64\Release\TinyTracer.dll C:\projects\tiny-tracer\install32_64\TinyTracer64.dll )
  - if [%buildPlatform%]==[x86] ( cp Release\TinyTracer.dll C:\projects\tiny-tracer\install32_64\TinyTracer32.dll )
 
artifacts:
  - path: install32_64
  
